version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:  # use increasingly general patterns to restore gradle cache
            - gradle-repo-v1-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
            - gradle-repo-v1-{{ checksum "AndroidDemo/build.gradle" }}-
            - gradle-repo-v1-
      - run:
          name: Build both the application and the AndroidTest APKs
          working_directory: AndroidDemo
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - save_cache:
          key: gradle-repo-v1-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
          paths:
            - ~/.gradle
      - save_cache:
          key: apk-cache-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - AndroidDemo/app/build/outputs/apk/debug/app-debug.apk
            - AndroidDemo/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - run:
          name: Run unit tests and lint
          command: |
            cd ./AndroidDemo
            ./gradlew lint test
      - store_artifacts:
          path: AndroidDemo/app/build/reports
          destination: reports
      - store_test_results:
          path: AndroidDemo/app/build/test-results
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - restore_cache:
          key: apk-cache-v1-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: |
            sudo gcloud firebase test android run \
              --app AndroidDemo/app/build/outputs/apk/debug/app-debug.apk \
              --test AndroidDemo/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=Nexus6P,version=26,locale=es,orientation=portrait  \
              --device model=walleye,version=28,locale=en,orientation=landscape \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            sudo pip install -U crcmod
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://cloud-test-${GOOGLE_PROJECT_ID} | tail -1` ${CIRCLE_ARTIFACTS}/ | true
          when: always
      - store_artifacts:
          path: ${CIRCLE_ARTIFACTS}
          destination: reports
      - store_test_results:
          path: ${CIRCLE_ARTIFACTS}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
